### ISSUE TITLE
[BUG]: incorrect colors for GitHub icon

### ISSUE THREAD

**Issue by denlove** [KislotaRU/KislotaRU#1]
https://github.com/KislotaRU/KislotaRU/blob/36a976b59cda1cc0df0be6125cbfb91b7b494c2d/README.md?plain=1#L20

### 1. Описание бага*
Иконка GitHub не видна в тёмной версии веб-интерфейса.

### 2. Какое поведение вызвало баг?*
Во время прочтения.

### 3. Ожидаемое поведение*
Предлагаю заменить имеющееся изображение на то, что в приложении ниже. Оно соотвествует общему стилю иконок, их расширению и должно быть хорошо видимым в любой выбранной теме интерфейса.

> [!NOTE]
> Варианты замены:
> 1. Можно просто заменить ссылку имеющейся иконки на ту, что ниже с приложением.
> 2. Скачать изображение в отдельную папку и вставить иконку с относительным адресом.

> [!WARNING]
> Необходима дополнительная проверка, потому что есть несколько вариантов ссылки.

### 4. Приложение

![mdi--github](https://github.com/user-attachments/assets/bcb31eaa-fddc-48a7-aaf1-4c30996d050f)

**Comment by KislotaRU** [comment]
Спасибо, @denlove, за обратную связь и предложение решений проблемы.
Заменил картинку другой с другим нейтральным серым цветом. Теперь и в светлой, и в тёмной теме видно замечательно.
